### ISSUE TITLE
Batch size configuration when using greedy decoding

### ISSUE THREAD

**Issue by YSLIU627** [bigcode-project/bigcodebench#36]
Hi, I am using your repo to evaluate starcoder2-15B. Though I have NVIDIA A100, the evaluation process is very slow (takes around 2.5 hours) After I check your code, I find that the batch size is set to 1 when using greedy decoding. Could you please update the configuration for faster evaluation with greedy decoding? Thanks.

**Comment by terryyz** [comment]
Hi @YSLIU627,

Thanks for using our benchmark! Just to clarify, which framework are you using for generation—vLLM or Transformers? We've noticed that the Transformers framework tends to be quite slow.

Our design for the generation batch size is similar to [EvalPlus](https://github.com/evalplus/evalplus/blob/4df700112e142efdebca6a7e8ce69882951f7532/codegen/generate.py#L157). The batch size is only used for the `N>1` samples per task instead of `N*K`, where `K` is the total number of tasks in the selected BigCodeBench set. This design choice ensures consistency throughout the generation process.

**Comment by YSLIU627** [comment]
Thanks for your reply. I am using the vLLM backend for the evaluation. I also used evalplus before but the code generation of evalplus is much faster.

**Comment by terryyz** [comment]
Thanks! I think the slower speed is mainly because BigCodeBench needs to generate a much longer context for certain tasks. For instance, EvalPlus sets max_new_tokens to 768, whereas we set it to 1280.

**Comment by YSLIU627** [comment]
Thanks for the explanation.
